// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZXDBahvBfknWJNBoQ-stsU55n3Rngohw',
    appId: '1:1089315100799:web:529d84d9d645c0657a874a',
    messagingSenderId: '1089315100799',
    projectId: 'myloginapi-a43ce',
    authDomain: 'myloginapi-a43ce.firebaseapp.com',
    storageBucket: 'myloginapi-a43ce.appspot.com',
    measurementId: 'G-BE6T417EEC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsrHFoy4o5WO0OT1wyI4-capPVmPDlof8',
    appId: '1:1089315100799:android:a6fe82905caca95e7a874a',
    messagingSenderId: '1089315100799',
    projectId: 'myloginapi-a43ce',
    storageBucket: 'myloginapi-a43ce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKAbY6sLVrxkk0M6WhxB-0yKnCLLrWUg0',
    appId: '1:1089315100799:ios:2c420f997614eb807a874a',
    messagingSenderId: '1089315100799',
    projectId: 'myloginapi-a43ce',
    storageBucket: 'myloginapi-a43ce.appspot.com',
    iosBundleId: 'com.example.assignmentlogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKAbY6sLVrxkk0M6WhxB-0yKnCLLrWUg0',
    appId: '1:1089315100799:ios:25ed2ff71989a9b07a874a',
    messagingSenderId: '1089315100799',
    projectId: 'myloginapi-a43ce',
    storageBucket: 'myloginapi-a43ce.appspot.com',
    iosBundleId: 'com.example.assignmentlogin.RunnerTests',
  );
}
